server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USER}:${MONGO_DB_PASS}@cluster0.2s8gm.mongodb.net/uber_user_db?appName=cluster0
  mongodb:
    uri: mongodb+srv://${MONGO_DB_USER}:${MONGO_DB_PASS}@cluster0.2s8gm.mongodb.net/uber_user_db?appName=cluster0

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

token:
  signing:
    key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
