server:
  port: 8083

spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  application:
    name: driver-service
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_DB_USER}:${MONGO_DB_PASS}@cluster0.2s8gm.mongodb.net/uber_driver_db?appName=cluster0
  mongodb:
    uri: mongodb+srv://${MONGO_DB_USER}:${MONGO_DB_PASS}@cluster0.2s8gm.mongodb.net/uber_driver_db?appName=cluster0

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
