package org.uber.userservice.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LoginResponse {
    /**
     * Placeholder token string.
     * In a production system, this would be a JWT generated by a dedicated Auth Service.
     */
    private String token;
    private UserResponse user;
}
